#########################
# REGISTER A NEW USER
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "firstName": "Sir",
    "lastName": "Arthur",
    "userName": "arthur",
    "email": "arthur@yahoo.com",
    "contactNumber": "074-550-1059",
    "password": "Shanara17!",
    "role": "tenant"
}

########################
# LOGIN EXISTING USER
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "emailOrUserName": "arthur",
    "password": "Shanara17!"
}