#########################
# REGISTER A NEW USER
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "firstName": "Maximus",
    "lastName": "Ochola",
    "userName": "max",
    "email": "maxi24@gmail.com",
    "contactNumber": "073-550-1059",
    "password": "Shanara17!",
    "role": "owner"
}

########################
# LOGIN EXISTING USER
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "emailOrUserName": "maxi24@gmail.com",
    "password": "Shanara17!"
}

######################
# FORGOT PASSWORD
POST http://localhost:4000/auth/forgot-password
Content-Type: application/json

{
    "emailOrUserName": "max"
}

#####################
# CHANGE PASSWORD
POST http://localhost:4000/auth/change-password
Content-Type: application/json

{
    "email": "maxi24@gmail.com",
    "newPassword": "Shanara17!",
    "confirmNewPassword": "Shanara17!"
}