###############
# ADD A NEW PROPERTY
POST http://localhost:4000/property/add/e0380cc0-f311-4b83-a537-4910808e60f2
Content-Type: application/json

{
	"name":"St.Joseph Apartments",
	"propertyType":"apartment",
	"details":{
        "description":"not just a house, but a home",
		"floors":"7",
		"rooms":"37",
		"accessories":{
			"wifi":"yes",
			"pool":"no",
			"parking":"yes"
		}
    },
	"location":{
		"addressLine":"046",
		"postalAddress":"0490",
		"cityOrTown":"Nairobi",
		"country":"Kenya"		
	},
    "status":"available"
}

